<div class="account-container zoom-anim-dialog mfp-hide dialog mfp-hide">


	<div ng-controller="AccountSevenCtrl" modal-reset="resetModal()">

		<div ng-if="tab == 'facebook'" class="dialog-padding account-modal">
			<p ng-show="account.user">
				Wir haben Dein Konto hier! Verknüpfe hier Dein Konto mit Facebook, damit Du Deine Daten nie wieder eingeben musst!
			</p>

			<p ng-show="!account.user">
				<b class="account-modal-bold">Hol dir dein Crunchbutton Account!</b><br>
				Log in or sign up using the same awesome button.
			</p>

			<div class="divider spacer-one-two"></div>

			<div class="button-pushable">
				<button class="button facebook" ng-click="facebook.auth()">
					<span ng-if="!facebook.facebook.wait">Nimm Facebook</span>
					<span ng-if="facebook.facebook.wait">Just a sec
						<div id="circleG">
							<div id="circleG_1" class="circleG"></div>
							<div id="circleG_2" class="circleG"></div>
							<div id="circleG_3" class="circleG"></div>
						</div>
					</span>
				</button>
			</div>

			<div class="no-auto-posting-message">No auto-posting, ever</div>

			<div class="dialog-message dialog-message-error" ng-repeat="error in account.errors">{{error}}</div>

			<span class="bottom-link cursor" ng-click="changeTab( 'form' )">Other Options</span>
		</div>


		<div ng-if="tab == 'form'">
			<div class="dialog-padding account-modal">
				<span ng-click="changeTab( 'facebook' )" class="back-link cursor"><span>&laquo;</span> BACK</span>
				<p>Kein Facebook Fan? Kein Problem. Wir erzählen's keinem. <b>Log in</b> or <b>sign up</b> below.</p>

				<div class="divider spacer-one-two"></div>

				<form name="accountForm">
					<div class="support-form-group form-group">
						<input type="email" ng-focus="softKeyboardModal($event)" maxlength="250" ng-model="account.form.email" name="email" tabindex="10" placeholder="email address" class="form-input form-field" ng-enter="account.enter()">
					</div>

					<div class="support-form-group form-group">
						<input type="password" ng-focus="softKeyboardModal($event)" class="form-input form-field" maxlength="250" ng-model="account.form.password" name="password" tabindex="11" placeholder="password" ng-enter="account.enter()">
					</div>
				</form>

				<div class="dialog-message dialog-message-error" ng-repeat="error in account.errors">{{error}}</div>

				<span class="help cursor" ng-click="changeTab( 'reset' )">Forgot Password</span>
				<div class="divider"></div>
			</div>
			<div class="dialog-divider"></div>
			<div class="dialog-padding dialog-bottom-buttons" ng-if="!support.thanks">
				<div class="button-pushable" ng-if="!account.processing">
					<button class="button account-submit lightorange" ng-click="account.enter()">Und rein!</button>
				</div>
				<div class="button-pushable" ng-if="account.processing">
					<button class="button account-submit lightorange">
						Just a sec
						<div id="circleG">
							<div id="circleG_1" class="circleG"></div>
							<div id="circleG_2" class="circleG"></div>
							<div id="circleG_3" class="circleG"></div>
						</div>
					</button>
				</div>

			</div>
		</div>


		<div ng-if="tab == 'reset'">
			<div class="dialog-padding account-modal">
				<span ng-click="changeTab('form')" class="back-link cursor"><span>&laquo;</span> BACK</span>

				<div ng-show="!help.success.visible">
					<p>Passwort vergessen? Hier neues machen!</p>

					<div class="divider spacer-one-onehalf"></div>

					<form name="accountReset" class="form">
						<div class="support-form-group form-group">
							<input type="email"  ng-focus="softKeyboardModal($event)" maxlength="250" ng-model="account.form.email" name="email" tabindex="10" placeholder="email address" class="form-input form-field" ng-enter="help.sendForm()">
						</div>
					</form>
				</div>

				<div class="dialog-message dialog-message-error" ng-repeat="error in help.errors">{{error}}</div>
				<div class="dialog-message dialog-message-success" ng-show="help.success.visible">
					Bitte check dein Email-Postfach oder Handy.
					<br/>
					Du bekommst einen Link zum Zurücksetzen, der 24 Stunden gültig ist.
				</div>
			</div>

			<div class="dialog-divider" ng-show="!help.success.visible"></div>
			<div class="dialog-padding dialog-bottom-buttons" ng-show="!help.success.visible">
				<div class="button-pushable" ng-show="!help.sendingHelpForm">
					<button class="button account-submit lightorange" ng-click="help.sendForm()">Passwort zurücksetzen</button>
				</div>
				<div class="button-pushable" ng-show="help.sendingHelpForm">
					<button class="button account-submit lightorange" disabled="disabled"><i class="fa fa-spinner fa-spin"></i> Senden</button>
				</div>
			</div>
		</div>

	</div>

</div>
