



				

<div class="cafe-top">
	<div class="top-pad"></div>

		<!-- home -->
		<div ng-show="home" class="cafe-home">
			<div class="double-content-padding">
				<br>
				<div class="cafe-logo-clean"></div>
				<br><br><br>
				<p>Es ist deine Aufgabe diese hungrigen Mäuler zu stopfen! Wenn du genug in der vorgegeben Zeit fütterst, ist der Sieg dein!</p>
				<br><br><br><br>
				<div class="cafe-start-toons"></div>
			</div>
		</div>
		
		<! -- game running -->
		<div ng-show="running" class="cafe-game">
			<div class="content-padding">
			
				<div class="cafe-message">
					<div class="dialog-message dialog-message-error" ng-show="message.error">
						<span ng-bind-html-unsafe="message.error"></span>
					</div>
					<div class="dialog-message dialog-message-success" ng-show="message.good">
						<span ng-bind-html-unsafe="message.good"></span>
					</div>
				</div>			

				<div class="cafe-request">
					<div class="cafe-bubble-wrap">
						<div class="bubble-request bubble-curved bubble-curved-green bubble-animated animated-resize" ng-show="requested.name">
							<div class="text">
								<span class="single-line"><b>{{requested.name}}</b></span>
							</div>
						</div>
						<div class="bubble-curved-spacer"></div>
					</div>
					<div class="about-green-orange animated-resize" ng-instant="winMessage = (winMessage > 11 ? 0 : (winMessage+1))" instant-pass-thru></div>
					<div class="divider"></div>
				</div>

				<div class="cafe-stats">
					<div class="stat-item">
						<div class="stat-key">Level:</div>
						<div class="stat-value">{{stats.round.name}}&nbsp;&nbsp;/&nbsp;&nbsp;{{difficulties[difficulty].name}}</div>
					</div>

					<div class="stat-item">
						<div class="stat-key">Orders:</div>
						<div class="stat-value">{{stats.success}}&nbsp;&nbsp;/&nbsp;&nbsp;{{stats.round.required}}</div>
					</div>
					
					<div class="stat-item">
						<div class="stat-key">Time:</div>
						<div class="stat-value"><span class="cafe-time-timer">{{stats.timer}}</span>&nbsp;/&nbsp;&nbsp;{{stats.round.time/1000}}:00</div>
					</div>
				</div>

			</div>
		</div>
		
		<! -- game endded win/lose -->
		<div ng-show="!running && !home" class="cafe-over">
			<div class="content-padding">
			
				<div class="cafe-stats">
					<div class="stat-item">
						<div class="stat-key">Level:</div>
						<div class="stat-value">{{stats.round.name}}&nbsp;&nbsp;/&nbsp;&nbsp;{{difficulties[difficulty].name}}</div>
					</div>

					<div class="stat-item">
						<div class="stat-key">Orders:</div>
						<div class="stat-value">{{stats.success}}&nbsp;&nbsp;/&nbsp;&nbsp;{{stats.round.required}}</div>
					</div>
					
					<div class="stat-item">
						<div class="stat-key">Time:</div>
						<div class="stat-value">{{stats.win ? stats.timer : stats.round.time/1000 + ':00'}}&nbsp;&nbsp;/&nbsp;&nbsp;{{stats.round.time/1000}}:00</div>
					</div>
					
					<div class="stat-item" ng-show="stats.win">
						<div class="stat-key">Punktzahl:</div>
						<div class="stat-value">{{stats.score}}</div>
					</div>
				</div>
				
				<br><br>
				<a href="" class="cafe-brag">Gib auf Facebook an</a>

				<div ng-show="stats.win">
					<div class="cafe-bubble-wrap">
						<div class="bubble-curved bubble-curved-green bubble-animated animated-resize">
							<div class="text" ng-switch="winMessage">
								<span class="single-line" ng-switch-when="1">Glückwunsch!</span>
								<span class="small" ng-switch-when="2">Du gewinnst eine Umarmung vom pinken Gorilla!</span>
								<span ng-switch-when="3">Wenn du einen finden kannst...</span>
								<span class="small" ng-switch-when="4" style="margin-top: -.3em">Du solltest damit bei allen deinen Freunden auf Facebook angeben!</span>
								<span class="small" ng-switch-when="5" style="margin-top: -.3em">Denn wen interessiert das denn nicht?!?</span>
								<span class="single-line" ng-switch-when="6">Nächstes Level!</span>
								<span class="single-line" ng-switch-when="7">Du schaffst das!</span>
								<span class="single-line" ng-switch-when="8">Ich glaub an dich!</span>
								<span class="single-line" ng-switch-when="9">Du machst das richtig gut!</span>
								<span class="single-line" ng-switch-when="10">Los geht's!</span>
								<span class="single-line" ng-switch-when="11">...jetzt!</span>
								<span class="single-line" ng-switch-when="12"><i class="fa fa-gamepad"></i> <i class="fa fa-gamepad"></i> <i class="fa fa-gamepad"></i></span>
								<span class="single-line" ng-switch-default><b>Du bist ein Gewinner!</b></span>
							</div>
						</div>
						<div class="bubble-curved-spacer"></div>
					</div>
					<div class="about-green-orange animated-resize" ng-instant="winMessage = (winMessage > 11 ? 0 : (winMessage+1))" instant-pass-thru></div>
					<div class="divider"></div>
					<p><br>Das war ja schon ziemlich einfach. Auf zum nächsten Level!</p>
				</div>
				
				<div ng-show="!stats.win">
					<div class="cafe-bubble-wrap">
						<div class="bubble-curved bubble-curved-red bubble-animated animated-resize">
							<div class="text" ng-switch="loseMessage">
								<span class="small" ng-switch-when="1">Naja, bestimmt ist es nicht deine Schuld...</span>
								<span class="small" ng-switch-when="2">Aber hier hast du auf jeden Fall versagt</span>
								<span class="single-line" ng-switch-when="3">Ich weiß, es ist ziemlich schwer</span>
								<span class="small" ng-switch-when="4" style="margin-top: -.3em">Aber es ist nicht im Vergleich dazu das Spiel zu programmieren.</span>
								<span class="single-line" ng-switch-when="5">Glaub ich.</span>
								<span ng-switch-when="6">Ich fühl mich, als ob ich mit mir selbst rede.</span>
								<span ng-switch-when="7">Ich glaub ich dreh durch!</span>
								<span class="single-line" ng-switch-when="8"><i class="fa fa-frown-o"></i> <i class="fa fa-smile-o"></i> <i class="fa fa-meh-o"></i></span>
								<span class="single-line" ng-switch-default><b>Du bist eher nicht su gut, oder?</b></span>
							</div>
						</div>
						<div class="bubble-curved-spacer"></div>
					</div>
					<div class="faq-tomato-green animated-resize" ng-instant="loseMessage = (loseMessage > 7 ? 0 : (loseMessage+1))" instant-pass-thru></div>
					<div class="divider"></div>
					<p><br>Lass uns das nochmal versuchen...</p>
				</div>
			</div>
		</div>

		<div class="divider"></div>
	</div>
	
	<div class="divider"></div>
	
	<div class="cafe-start" ng-show="!running">
		<div class="double-content-padding">
			<button class="pushable button pink pushable big ani-all" ng-click="start()">
				<span ng-show="home">Start</span>
				<span ng-show="!home && stats.win">Nächstes Level</span>
				<span ng-show="!home && !stats.win">Nochmal versuchen</span>
			</button>
		</div>
	</div>
	
	<div class="cafe-buttons" ng-show="running">
		<div class="content-padding">
			<button class="cafe-button {{button.id}}" ng-repeat="button in items" ng-instant="buttonPress(button.id)">{{button.name && stats.round.descriptions ? button.name : ''}}</button>
		</div>
	</div>
	
	<div class="cafe-button cafe-preload {{button.id}}" ng-repeat="button in allitems"></div>
</div>
