<div class="top-pad"></div>

<div class="faq-bubble-wrap noselect">
	<div class="bubble-tailless bubble-tailless-green">
		<div class="text">
			<b>&nbsp;&nbsp;Keine Sorge!</b><br />
			Wir sind hier um dir zu helfen!
		</div>
	</div>
	<div class="faq-tomato"></div>
	<div class="divider"></div>
</div>

<br /><br /><br />
<div class="content-padding col-box" ng-controller="SupportCtrl">
	<div class="two-col">
		<br />
		<h4>Also, was ist dieses Crunchbutton?</h4>
		<p>Der Ami würde sagen: Get food delivered from places that don't deliver. Place an order, and we save it for next time, along with your delivery and payment info. Come back and reorder your favorites with just one click.</p>
	</div>
	<div class="two-col">
		<h4>Willst du Crunchbutton kontaktieren?</h4>
		<p>Tja, da bist du ein paar Jahre zu spät dran, Crunchbutton ist pleite.</p>
		<!--<p>Problem with your order? Need help with your homework? Text us at <a href="sms:+16467831444">(646) 783-1444</a> or email us at <a href="mailto:{{happy_customers}}">{{happy_customers}}</a> or <a href="mailto:{{angry_customers}}">{{angry_customers}}</a>, as appropriate.</p>-->
		<br /><br />
		<button class="button green" ng-click="support.dialog()">Schick uns ne Nachricht</button>
	</div>
</div>


<div class="content-padding">
	<br /><br /><br /><br /><br /><br />
	<div class="faq-sun"></div>
	<br /><br /><br /><br />
</div>

<div class="content-padding col-box hide-desktop">

	<div class="two-col">
		<h4>Wer wart ihr?!</h4>
		<p>We're people! People who love food so much that we want to share our passion without asking you to even leave your homes.</p>
		<br>
		<button class="button lightorange" ng-click="navigation.link('/about','push')">Meet the team</button>
	</div>

	<div class="two-col">
		<h4>Wie bestelle ich was?</h4>
		<p>Geh zu <a href="http://crunchbutton.com" target="_system">crunchbutton.com</a> und klicke auf das Restaurant von dem du bestellen willst. Klick die gewünschten Gerichte an, um sie in den Warenkorb zu packen. Klicke auf "Bestellung aufgeben" und versuche hungrig zu bleiben! Der Fahrer ruft dich an oder klingelt, sobalt er da ist.</p>
	</div>

	<div class="two-col">
		<h4>Aber ich hab Crunchbutton vorher noch nie benutzt...</h4>
		<p>Hey, ist okay. Ich erinner mich auch noch an mein erstes Mal. I bin zu Crunchbutton.com gesurft, hab mein Lieblingsrestaurant gefunden, auf "Bestellung aufgeben" geklickt und Minuten später hatte ich mein Sandwich in der Hand.</p>
	</div>

		<div class="two-col">
		<h4>Wie schützt ihr meine Daten?</h4>
		<p>Wir benutzen SSL um deine Daten zu übertragen. Außerdem speichern wir deine Zahlungsdaten nicht dauerhaft auf unseren Servern.</p>
	</div>
	<div class="two-col">
		<h4>Wie kann ich meine Daten ändern?</h4>
		<p>Klick sie an, ändere sie und sobald du deine nächste Bestellung aufgibst werden sie übernommen.</p>
	</div>
	
	<div class="two-col">
		<h4>Hast du wirklich das ganze FAQ übersetzt?</h4>
		<p>Nein, hier hab ich aufgehört.</p>
	</div>


	<div class="two-col">
		<h4>omg i am wayy too drunk to enter my information</h4>
		<p>We thought this might happen. Luckily, Crunchbutton saves your address, phone, and payment info, so all you have to do is click what you want and hit the big, red "Submit Order" button. Try to be awake when the delivery guy calls.</p>
	</div>



	<div class="two-col">
		<h4>I want to put a restaurant on Crunchbutton.</h4>
		<p>Good idea! <a ng-click="navigation.link('/owners','push')">Get more info and contact us</a>.</p>
	</div>



	<div class="two-col">
		<h4>I want to deliver food myself!</h4>
		<p>Cool! <a ng-click="navigation.link('/drivers/apply','push')">Fill out an application here</a>.</p>
	</div>



	<div class="two-col">
		<h4>I know I can order food online, but can I order by US mail?</h4>
		<p>Why yes you can! Give us one week's notice, and we will get you your food! Send a check or money order to:
		Crunchbutton, 1120 Princeton Dr STE 7, Marina Del Rey, CA 90292</p>
	</div>


	<div class="two-col">
		<h4>I know I can order food by US mail, but can I order by teleportation?</h4>
		<p>Why yes you can! Send a check or money order to Crunchbutton, 1120 Princeton Dr STE 7, Marina Del Rey, CA 90292, give us 25 years to develop the appropriate technology, and we will get you your food!</p>
	</div>

	<div class="two-col">
		Visit our <a ng-click="navigation.link('/legal','push')">legal page</a> for legal and privacy information.
	</div>
</div>

<div class="content-padding col-box hide-mobile">

	<div class="two-col">
		<h4>Who are you?!</h4>
		<p>We're people! People who love food so much that we want to share our passion without asking you to even leave your homes.</p>
		<br>
		<button class="button lightorange" ng-click="navigation.link('/about','push')">Meet the team</button>
	</div>

	<div class="two-col">
		<h4>omg i am wayy too drunk to enter my information</h4>
		<p>We thought this might happen. Luckily, Crunchbutton saves your address, phone, and payment info, so all you have to do is click what you want and hit the big, red "Submit Order" button. Try to be awake when the delivery guy calls.</p>
	</div>

	<div class="two-col">
		<h4>How do I order food?</h4>
		<p>Easy! Just go to <a href="http://crunchbutton.com" target="_system">crunchbutton.com</a> and click the restaurant you want to order from. Add whatever food you want, and enter your address, phone, and payment info. Click "Submit Order" and try to stay hungry! The driver will call you when they're outside.</p>
	</div>

	<div class="two-col">
		<h4>I want to put a restaurant on Crunchbutton.</h4>
		<p>Good idea! <a ng-click="navigation.link('/owners','push')">Get more info and contact us</a>.</p>
	</div>

	<div class="two-col">
		<h4>But I've never used Crunchbutton before...</h4>
		<p>Oh man, it's okay. I remember my first time, it didn't last more than 30 seconds. I went to Crunchbutton.com, found my favorite restaurant, hit "Submit Order." Minutes later, my sandwich arrived. Post-coital bliss ensued, that sandwich sure knew how to crunch my buttons.</p>
	</div>

	<div class="two-col">
		<h4>I want to deliver food myself!</h4>
		<p>Cool! <a ng-click="navigation.link('/drivers/apply','push')">Fill out an application here</a>.</p>
	</div>


	<div class="two-col">
		<h4>How do you save my info?</h4>
		<p>We use SSL and a PCI-DSS Level 1 Compliant provider to encrypt your information when you place an order. We never store any of your financial information on our web servers.</p>
	</div>

	<div class="two-col">
		<h4>I know I can order food online, but can I order by US mail?</h4>
		<p>Why yes you can! Give us one week's notice, and we will get you your food! Send a check or money order to:
		Crunchbutton, 1120 Princeton Dr STE 7, Marina Del Rey, CA 90292</p>
	</div>


	<div class="two-col">
		<h4>How do I change my stored info?</h4>
		<p>Just click on the info you want to change, enter the changes, and, after you place your order, it’ll be saved for next time.</p>
	</div>

	<div class="two-col">
		<h4>I know I can order food by US mail, but can I order by teleportation?</h4>
		<p>Why yes you can! Send a check or money order to Crunchbutton, 1120 Princeton Dr STE 7, Marina Del Rey, CA 90292, give us 25 years to develop the appropriate technology, and we will get you your food!</p>
	</div>

	<div class="two-col">
		Visit our <a ng-click="navigation.link('/legal','push')">legal page</a> for legal and privacy information.
	</div>
</div>

<br /><br /><br /><br /><br /><br /><br />
<center><div class="fa fa-heart faq-heart"></div></center>
<br /><br /><br /><br />
