<div class="bg">
	<div class="home-top parallax-bg">
		<div class="top-pad"></div>

		<div class="home-inputs">
		<div class="splash-inputs">

			<div class="cafe-bubble-wrap">
				<div class="bubble-curved bubble-curved-white bubble-animated animated-resize">
					<div class="text" ng-switch="loseMessage">

						<span class="small" ng-switch-when="1">Sag uns Bescheid, dass du crunchbutton</span>
						<span class="small" ng-switch-when="2">brauchst und wir strengen <br> uns an, bald da zu sein!</span>
						<span class="small" ng-switch-when="3">Interessiert deine Gemeinschaft zu vertreten?</span>
						<span class="small" ng-switch-when="4">Wie wär's damit Essen auszufahren?</span>
						<span class="small" ng-switch-when="5">Geh auf die Jobs Seite und sag uns Bescheid</span>
						<span class="single-line" ng-switch-when="6"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
						<span class="small" ng-switch-default><b>Starte deine eigene Lieferfirma!</b></span>

					</div>
				</div>
				<div class="bubble-curved-spacer"></div>
			</div>
			<div class="faq-tomato-green animated-resize" ng-instant="loseMessage = (loseMessage > 6 ? 0 : (loseMessage+1))" instant-pass-thru></div>
			<div class="divider spacer-one-two"></div>

			<div ng-if="!complete">

				<div ng-show="!show_form">
					<p>
						Willst du dein eigenes Geschäft machen? Starte crunchbutton für deine Gemeinde!
						<br><br>
						Crunchbutton stellt dir die Ressourcen bereit, dass zu tun. Starte dein eigenes Geschäft mit der Crunchbutton technologie
					</p>

					<div class="divider spacer-one-two"></div>

					<div class="button-pushable">
						<button class="button orange" ng-click="show_form = true;">
							<div><b>Bring Crunchbutton zu mir</b></div>
						</button>
					</div>

					<div class="divider spacer-one-one"></div>

					<p class="center-text">
						<a href="" class="splash-continue" ng-instant="navigation.link('/location')">Versuchs woanders</a>
					</p>

				</div>

				<div ng-show="show_form">

					<div class="divider spacer-one-one"></div>

					<div class="run-business-error" ng-if="submitted && !contact.name">Namen eingeben</div>
					<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="Name"  ng-model="contact.name">

					<div class="run-business-error" ng-if="submitted && !contact.phone">Telefonnummer eingeben</div>
					<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="Phone"  ng-model="contact.phone">

					<div class="run-business-error" ng-if="submitted && !contact.email">E-Mail eingeben</div>
					<div class="run-business-error" ng-if="submitted && email_invalid">GÜLTIGE E-Mail eingeben</div>
					<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="Email"  ng-model="contact.email">

					<div class="run-business-error" ng-if="submitted && !contact.address">Adresse eingeben</div>
					<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="Address"  ng-model="contact.address">

					<div class="run-business-error" ng-if="submitted && !contact.reason">Warum wärst du dazu geeignet?</div>
					<textarea class="run-business-textarea" autocapitalize="off" autocorrect="off" placeholder="Warum ich toll bin:" ng-model="contact.reason"></textarea>

					<div class="button-pushable">
						<a class="button orange" ng-click="sendMessage()">
							<div><b>Send</b></div>
						</a>
					</div>

					<p class="center-text">
						<a href="" class="splash-continue small" ng-click="show_form = false;">Abbrechen</a>
					</p>

				</div>

			</div>

			<div ng-if="complete" class="run-business-thank-you">
				<p>Dankeschön!</p>
			</div>


			<? /*
			<div ng-if="account.user.id_user && !recommend.greetings">
				<h4>We don't serve that address yet.</h4>
				<p>But you can recommend something. Let us know what you want to see on crunchbutton!</p>
				<div class="divider spacer-one-two"></div>

				<input class="location-recommend" autocapitalize="off" autocorrect="off" placeholder="e.g. Alpha Delta Pizza" ng-enter="recommend.send()" ng-model="recommend.form.restaurant">

				<div class="button-pushable">
					<button class="button orange" ng-click="recommend.send()"><b>Recommend</b></button>
				</div>
			</div>


			<div ng-if="recommend.greetings">
				<h4>Sent to our brains!</h4>
				<p>We will let you know soon! Thanks for trying crunchbutton!</p>
			</div>
			*/ ?>

		</div>


		</div>
	</div>

	<div ng-include src="'/assets/view/location.bottom.html'"></div>
</div>
