
	<div class="divider-orange-food divider-circle" ng-click="scrollHalf()"></div>

	<br /><br /><br />
	<div class="content-padding home-buttons col-box">
		<div class="two-col">
			<h4>Dein Lieblingsrestaurant, mit Lieferservice</h4>
			<p>Lassen Sie sich Lebensmittel von Orten liefern, die nicht liefern. Geben Sie eine Bestellung auf und wir speichern sie für das nächste Mal zusammen mit Ihren Liefer- und Zahlungsinformationen. Kommen Sie zurück und ordnen Sie Ihre Favoriten mit nur einem Klick neu.</p>
			<br><br><br>

			<div class="location-gorillia hide-desktop" ng-click="rage()"></div>

			<h4>Wer seid ihr?!</h4>
			<p>Wir sind Menschen! Menschen, die das Essen so sehr lieben, dass wir unsere Leidenschaft teilen möchten, ohne Sie zu bitten, Ihr Zuhause zu verlassen.</p>
			<br>
			<button class="button lightorange" ng-click="navigation.link('/about','push')">Triff das Team</button>
		</div>
		<div class="two-col hide-mobile">
			<div class="location-gorillia animated-resize" ng-click="rage()"></div>
		</div>
	</div>

	<div class="divider dots spacer-two-one"></div>


	<div class="about-join-bubble-wrap">
		<div class="bubble-curved bubble-curved-green bubble-animated animated-resize">
			<div class="text" ng-switch="orangeMessage">
				<span class="small" ng-switch-when="1">So you can write stupid messages like this</span>
				<span ng-switch-when="2">That no one will ever read</span>
				<span ng-switch-when="3">So you could put anything</span>
				<span class="single-line" ng-switch-when="4">No really.</span>
				<span class="single-line" ng-switch-when="5">Like...</span>
				<span class="single-line" ng-switch-when="6">"Hi Crystal!"</span>
				<span ng-switch-when="7">Did I mention we like beer?</span>
				<span class="single-line" ng-switch-when="8">Yeah we do.</span>
				<span ng-switch-when="9">We even brew our own beer</span>
				<span class="small" ng-switch-when="10">That just screams cool right there</span>
				<span class="single-line" ng-switch-when="11"><i class="fa fa-beer"></i> <i class="fa fa-beer"></i> <i class="fa fa-beer"></i></span>
				<span class="single-line" ng-switch-default><b>Join us!</b></span>
			</div>
		</div>
		<div class="bubble-curved-spacer"></div>
	</div>
	<div class="about-green-orange animated-resize" ng-instant="orangeMessage = (orangeMessage > 10 ? 0 : (orangeMessage + 1))" instant-pass-thru></div>
	<div class="divider"></div>
	<br><br>

	<div class="content-padding home-buttons col-box" ng-controller="SupportCtrl">
		<div class="three-col">
			<h4>Delivery Drivers</h4>
			<p>
				Was gibt es Schöneres, als Essen geliefert zu bekommen? Essen liefern! Wenn Sie ein Smartphone, ein Auto und eine Autoversicherung haben, senden Sie uns eine Nachricht!
			</p>
			<br />
			<a href ng-click="navigation.link('/drivers/apply','push')"><button class="button green">Jetzt mitmachen</button></a>
			<br /><br /><br /><br />
		</div>

		<div class="three-col">
			<h4>Marketing Interns</h4>
			<p>
				Niemand weiß mehr über Ihr College oder Ihre Gemeinde als Sie. Sie wissen, was "cool" ist, und deshalb werden wir mit Ihnen zusammenarbeiten! Suchen Sie nach lokalen fantastischen Restaurants, um sich anzumelden, und spielen Sie eine wichtige Rolle bei der Orchestrierung von Marketingkampagnen.

			</p>
			<br />
			<a href="mailto:{{reps}}"><button class="button green">Join up</button></a>
			<br /><br /><br /><br />
		</div>

		<div class="three-col">
			<h4>Rockstar Developers &amp; Designers</h4>
			<p>Schauen Sie sich diese schöne Website an! Es ist fast perfekt! Weißt du was es besser machen würde? Deine magische Note! Treten Sie unserem kleinen Entwicklerteam in Obernburg bei und lassen Sie uns Gemeinsame Sache machen!</p>
			<br />
			<a href="mailto:{{devs}}"><button class="button green">Rock Out</button></a>
		</div>

		<!--
		<div class="three-col">
			<a href ng-click="navigation.link('/drivers/apply','push')"><button class="button lightorange">Apply Now</button></a>
		</div>
		<div class="three-col">
			<a href="mailto:{{reps}}"><button class="button lightorange">Join up</button></a>
		</div>
		<div class="three-col">
			<a href="mailto:{{devs}}"><button class="button lightorange">Rock Out</button></a>
		</div>
-->
	</div>

	<div class="divider dots spacer-two-two"></div>
	<br><br>


	<div class="col-box content-padding">
		<div class="two-col">
			<div class="location-map"></div>
		</div>
		<div class="two-col">

				<h4>We’re expanding!</h4>
				<p>Wir sind vielleicht noch nicht überall, aber die Gemeinschaften, in die wir verliebt sind, lieben uns! Stöbern Sie in einigen der beliebtesten Restaurants:</p>
				<br /><br /><br />
				<p>
					<span class="popular-location" ng-repeat="alias in topCommunities">
						<a href="/{{alias.alias}}">{{alias.name}}</a>
					</span>
				</p>

		</div>
	</div>
