
	<div class="divider-orange-food divider-circle" ng-click="scrollHalf()"></div>

	<br /><br /><br />
	<div class="content-padding home-buttons col-box">
		<div class="two-col">
			<h4>Dein Lieblingsrestaurant, mit Lieferservice</h4>
			<p>Lass dich von Orten beliefern, die nicht liefern. Geben Sie eine Bestellung auf und wir speichern sie für das nächste Mal zusammen mit Ihren Liefer- und Zahlungsinformationen. Kommen Sie zurück und ordnen Sie Ihre Favoriten mit nur einem Klick neu.</p>
			<br><br><br>

			<div class="location-gorillia hide-desktop" ng-click="rage()"></div>

			<h4>Wer seid ihr?!</h4>
			<p>Wir sind Menschen! Menschen, die das Essen so sehr lieben, dass wir unsere Leidenschaft teilen möchten. Und dass ohne dich zu bitten dein Zuhause zu verlassen.</p>
			<br>
			<button class="button lightorange" ng-click="navigation.link('/about','push')">Triff das Team</button>
		</div>
		<div class="two-col hide-mobile">
			<div class="location-gorillia animated-resize" ng-click="rage()"></div>
		</div>
	</div>

	<div class="divider dots spacer-two-one"></div>


	<div class="about-join-bubble-wrap">
		<div class="bubble-curved bubble-curved-green bubble-animated animated-resize">
			<div class="text" ng-switch="orangeMessage">
				<span class="small" ng-switch-when="1">Also kann man hier dämlich Nachrichten schreiben</span>
				<span ng-switch-when="2">Die wird niemals irgendwer lesen</span>
				<span ng-switch-when="3">Du könntest hier alles hinschreib</span>
				<span class="single-line" ng-switch-when="4">Echt jetzt.</span>
				<span class="single-line" ng-switch-when="5">Zum Beispiel...</span>
				<span class="single-line" ng-switch-when="6">"Hallo Martin!"</span>
				<span ng-switch-when="7">Haben wir schon erwähnt, dass wir Bier mögen?</span>
				<span class="single-line" ng-switch-when="8">Ja, das tun wir.</span>
				<span ng-switch-when="9">Wir brauen sogar uns eigenes Bier</span>
				<span class="small" ng-switch-when="10">Wir sind schon tolle Leute.</span>
				<span class="single-line" ng-switch-when="11"><i class="fa fa-beer"></i> <i class="fa fa-beer"></i> <i class="fa fa-beer"></i></span>
				<span class="single-line" ng-switch-default><b>Mach mit!</b></span>
			</div>
		</div>
		<div class="bubble-curved-spacer"></div>
	</div>
	<div class="about-green-orange animated-resize" ng-instant="orangeMessage = (orangeMessage > 10 ? 0 : (orangeMessage + 1))" instant-pass-thru></div>
	<div class="divider"></div>
	<br><br>

	<div class="content-padding home-buttons col-box" ng-controller="SupportCtrl">
		<div class="three-col">
			<h4>Fahrer</h4>
			<p>
				Was gibt es Schöneres, als Essen geliefert zu bekommen? Essen liefern! Wenn Sie ein Smartphone, ein Auto und eine Autoversicherung haben, senden Sie uns eine Nachricht!
			</p>
			<br />
			<a href ng-click="navigation.link('/drivers/apply','push')"><button class="button green">Jetzt bewerben</button></a>
			<br /><br /><br /><br />
		</div>

		<div class="three-col">
			<h4>Marketing Praktikanten</h4>
			<p>
				Niemand weiß mehr über Ihr College oder Ihre Gemeinde als Sie. Sie wissen, was "cool" ist, und deshalb werden wir mit Ihnen zusammenarbeiten! Suchen Sie nach lokalen fantastischen Restaurants, um sich anzumelden, und spielen Sie eine wichtige Rolle bei der Orchestrierung von Marketingkampagnen.

			</p>
			<br />
			<a href="mailto:{{reps}}"><button class="button green">Mach mit</button></a>
			<br /><br /><br /><br />
		</div>

		<div class="three-col">
			<h4>Entwickler &amp; Designer</h4>
			<p>Schauen Sie sich diese "wundervolle" Website an! Es ist fast perfekt! Weißt du was es besser machen würde? Deine magische Note! Treten Sie unserem kleinen Entwicklerteam bei und lassen Sie uns Gemeinsame Sache machen!</p>
			<br />
			<a href="mailto:{{devs}}"><button class="button green">Los geht's</button></a>
		</div>

		<!--
		<div class="three-col">
			<a href ng-click="navigation.link('/drivers/apply','push')"><button class="button lightorange">Apply Now</button></a>
		</div>
		<div class="three-col">
			<a href="mailto:{{reps}}"><button class="button lightorange">Join up</button></a>
		</div>
		<div class="three-col">
			<a href="mailto:{{devs}}"><button class="button lightorange">Rock Out</button></a>
		</div>
-->
	</div>

	<div class="divider dots spacer-two-two"></div>
	<br><br>


	<div class="col-box content-padding">
		<div class="two-col">
			<div class="location-map"></div>
		</div>
		<div class="two-col">

				<h4>Wir wachsen!</h4>
				<p>Wir sind vielleicht noch nicht überall, aber die Gemeinschaften, in die wir verliebt sind, lieben uns! Stöbern Sie in einigen der beliebtesten Restaurants:</p>
				<br /><br /><br />
				<p>
					<span class="popular-location" ng-repeat="alias in topCommunities">
						<a href="/{{alias.alias}}">{{alias.name}}</a>
					</span>
				</p>

		</div>
	</div>
