<div class="top-pad"></div>

<div ng-if="!order.id">
	<div class="content-padding">
		<div class="ajax-loader-teal"></div>
		<br />
	</div>
</div>

<div ng-if="order.id">


	<div class="">

		<div class="content-padding">
			<div class="order-tagline"><p>
				<b>Ist gebongt!&nbsp;</b>
				Deine Bestellung ist bei uns eingegangen.
			</p></div>
		</div>

		<div class="divider dots"></div>
		<div class="spacer-two-two"></div>

		<div class="content-padding-desktop">

			<div class="content-padding-mobile">

				<div ng-hide="account.user.has_auth">
					<div class="order-buttons">
						<p>
							Erstell einen Account und verdiene {{order.reward.points}} Punkte.
						</p>
						<br>
						<div class="button-pushable">
							<button class="button lightorange" ng-click="modal.signupOpen();">Account erstellen</button>
						</div>
						<br />
					</div>

				</div>

				<div ng-show="account.user.has_auth">

					<div class="order-buttons">
						<p ng-if="account.user.points.free_delivery_message && account.user.points.free_delivery" class="delivery-free order-delivery-free">
							Du hast <strong>{{account.user.points.show}}</strong> Punkte! Das nächste mal gehen die Liefergebühren auf uns.
						</p>
						<div ng-if="!account.user.points.free_delivery_message">
							<p class="delivery-free points-earned-message">
								Du hast gerade <strong>{{order.reward.points}}</strong> Punkte verdien!
								<span ng-if="!account.user.points.free_delivery_message">
									Wenn du <strong> {{account.user.points.free_delivery}}</strong> Punkte hast, übernehmen wir einmal deine Liefergebühren.
								</span>
							</p>
						</div>

					</div>
				</div>

			</div>
			<div class="content-padding-mobile" ng-show="account.user.has_auth">

				<!-- <div class="col-box"> -->

					<div class="hide-desktop button-refer-big">
						<a href="{{referral.sms}}">
							<button class="button lightorange">
								<i class="fa fa-comment"></i>&nbsp;&nbsp;&nbsp;<span>Freunde einladen</span>
							</button>
						</a>
					</div>

					<div class="button-refer-big">
						<span class="refer-multiply hide-mobile">Doppelte Punkte, wenn du die Bestellung auf Facebook teilst</span>
						<span class="refer-multiply-small hide-desktop">Doppelte Punkte, wenn du die Bestellung auf Facebook teilst</span>

						<button class="button facebook" ng-click="referral.facebook('order');" ng-if="account.user.has_auth && !order.reward.shared.facebook">
							<i class="fa fa-facebook-square"></i> <span>Teilen</span>
						</button>
					</div>

					<div class="button-refer-big">
						<span class="refer-multiply hide-mobile">Dreifache Punkte, wenn du die Bestellung auf Twitter teilst</span>
						<span class="refer-multiply-small hide-desktop">Dreifache Punkte, wenn du die Bestellung auf Twitter teilst</span>
						<button class="button twitter" ng-click="referral.twitter('order')" ng-if="account.user.has_auth && !order.reward.shared.twitter">
							<i class="fa fa-twitter-square"></i> <span>Tweet</span>
						</button>
					</div>

				<!-- </div> -->

				<div ng-if="order.reward.shared.facebook">
					Danke, fürs Teilen auf Facebook.
				</div>

				<div ng-if="order.reward.shared.twitter">
					Danke, fürs Teilen auf Twitter.
				</div>
				<div class="divider"></div>
				<br><br>
				<div class="content-padding">
					<p class="center-text">
						Gratis Liefergebühren für jeden, der mit deinem Link die erste Bestellung tätigt.
						<br><br>
					</p>
				</div>

			</div>

		</div>

		<div class="divider dots"></div>
		<div class="spacer-two-two"></div>

		<div class="content-padding-desktop">
			<div class="content-padding-mobile">

				<div class="order-bubble-wrap">
					<div class="bubble-tail bubble-tail-green bubble-animated">
						<div class="text" ng-switch="cherryMessage">
							<span ng-switch-when="1">Dein Essen ist bestellt.</span>
							<span ng-switch-when="2" class="single-line">Yay! Essen!</span>
							<span ng-switch-when="3">Fragen? Kontaktiere das Restaurant.</span>
							<span ng-switch-when="4">Feedback? Schreib uns eine Nachricht.</span>
							<span ng-switch-when="5">Wir freuen uns, von dir zu hören.</span>
							<span ng-switch-when="6">Vorschläge oder sogar Beschwerden</span>
							<span ng-switch-when="7" class="single-line">Wir hören dir zu!</span>
							<span class="single-line" ng-switch-when="8"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
							<span ng-switch-default><b>Lehn dich zurück &amp entspann dich!</b></span>
						</div>
						<div class="bubble-tail-spacer"></div>
					</div>
					<div class="hot-dog-relax animated-resize" ng-instant="cherryMessage = (cherryMessage > 7 ? 0 : (cherryMessage + 1))" instant-pass-thru></div>
					<div class="divider"></div>
				</div>
			</div>

			<div class="divider"></div>

			<div class="spacer-two-two"></div>

		</div>

		<div class="content-padding">
			<p class="center-text">
				Für mehr Informationen zu deiner Bestellung, kannst du dir die  <a ng-click="receipt()">Bestellungs Details</a> anschauen.
			</p>
		</div>
		<div class="content-padding">
			<p class="notes-text">
				Wenn du deine Bestellung abbrechen oder änder willst, ruf uns  <a href="tel:+4915253985136">(+49) 1525 3985136</a> innerhalb von 10 Minuten nach Bestellungseingang an, dann schauen wir was wir tun können.
			</p>
		</div>




	</div>

</div>
