<div class="top-pad"></div>

<div>
	<?php /*
	<div class="content-padding">
		<div ng-if="order.delivery_service && order.status.status != 'delivered'">
			<div class="order-status-loader-labels">
				<div class="order-status-loader-label">{{order._time}}</div>
				<div class="order-status-loader-label"></div>
				<div class="order-status-loader-label"></div>
				<div class="order-status-loader-label" ng-if="order.status.status != 'delivered'">ETA:&nbsp;
					<span ng-show="(order.delivery_type == 'delivery')">{{order._restaurant_delivery_estimated_time_formated}}</span>
					<span ng-hide="(order.delivery_type == 'delivery')">{{order._restaurant_pickup_estimated_time_formated}}</span>
				</div>
				<div class="order-status-loader-label" ng-if="order.status.status == 'delivered' && 1==2">
					{{order.status.date}}
				</div>

			</div>
			<div class="order-status-loader">
				<div class="order-status-loader-block order-status-loader-active" >&nbsp;</div>
				<div class="order-status-loader-block" ng-class="{'order-status-loader-active': order.status.status != 'new'}">&nbsp;</div>
				<div class="order-status-loader-block" ng-class="{'order-status-loader-active': order.status.status != 'new' && order.status.status != 'accepted'}">&nbsp;</div>
				<div class="order-status-loader-block" ng-class="{'order-status-loader-active': order.status.status == 'delivered'}">&nbsp;</div>
			</div>
			<div class="order-status-loader-labels">
				<div class="order-status-loader-label">Ordered</div>
				<div class="order-status-loader-label">Accepted</div>
				<div class="order-status-loader-label">Picked up</div>
				<div class="order-status-loader-label">Delivered</div>
			</div>
		</div>
		<div class="divider"></div>
	</div>
	<div class="divider dots spacer-one-two" ng-if="order.delivery_service && order.status.status != 'delivered'"></div>
	*/?>



	<div class="content-padding-desktop">

		<div class="content-padding-mobile">
			<div ng-hide="account.user.has_auth">
				<div class="order-buttons">
					<p>
						Erstell einen Account und verdiene {{order.reward.points}} Punkte für einmal <b>gratis Liefergebühren</b> und bestell dein Essen von überall, wie <a data-ng-href="http://crunchbutton.com">crunchbutton.com</a> oder unsere&nbsp;
						<a ng-show="!isAndroid" data-ng-href="https://itunes.apple.com/app/id721780390">iOS App</a>
						<a ng-show="isAndroid" data-ng-href="https://play.google.com/store/apps/details?id=com.crunchbutton">Android App</a>
					</p>

					<br>
					<div class="button-pushable">
						<button class="button lightorange" ng-click="modal.signupOpen();">Account erstellen</button>
					</div>
					<br />
				</div>

			</div>

			<div ng-show="account.user.has_auth">

				<div class="order-buttons">

					<div class="col-box">
						<p class="two-col">
							Willst du einmal gratis Liefergebühren? Auf Facebook oder Twitter teilen, um Punkte zu verdienen<span ng-if="referral.invite_url && referral.enabled"></span>.
							<br><br>
						</p>

						<div class="hide-desktop button-refer">
							<a href="{{referral.sms}}">
								<button class="button lightorange">
									<i class="fa fa-comment"></i>&nbsp;&nbsp;&nbsp;<span>Freunde einladen</span>
								</button>
							</a>
						</div>

						<div class="two-col">
							<div class="col-box">
								<div class="button-refer">
									<span class="refer-multiply hide-mobile">Verdoppel deine Punkte</span>
									<span class="refer-multiply-small hide-desktop">Verdoppel deine Punkte, indem du uns auf Facebook teilst</span>
									<button class="button facebook" ng-click="referral.facebook('order');" ng-if="account.user.has_auth && !order.reward.shared.facebook">
										<i class="fa fa-facebook-square"></i> <span>Teilen</span>
									</button>
								</div>

								<div class="button-refer">
									<span class="refer-multiply hide-mobile">Dreifach punkten!</span>
									<span class="refer-multiply-small hide-desktop">Dreifach Punkten, indem du uns auf Twitter teilst.</span>
									<button class="button twitter" ng-click="referral.twitter('order')" ng-if="account.user.has_auth && !order.reward.shared.twitter">
										<i class="fa fa-twitter-square"></i> <span>Tweet</span>
									</button>
								</div>

							</div>
							<div ng-if="order.reward.shared.facebook">
								Danke, dass du uns gefacebookt hast.
							</div>

							<div ng-if="order.reward.shared.twitter">
								Danke, dass du uns getwittert hast.
							</div>
						</div>


						<div class="divider"></div>

					</div>




				</div>
			</div>

		</div>
	</div>

	<div class="divider dots" ng-if="order.id"></div>
	<br><br>


	<div class="order-content col-box content-padding-desktop" ng-if="order.id">

		<div class="content-padding-mobile two-col">

			<div class="order-icon"><div class="icon-chef"></div></div>
			<div class="order-info">
				<p ng-if="order.delivery_service == 1">
					Wenn du Fragen zu deiner Bestellung hast, schreib deinem Fahrer eine Nachricht. Die Nummer wir dir geschickt.
				</p>
				<p ng-if="order.delivery_service == 0">
					Wenn du Fragen zu deiner Bestellung hast, kannst du hier anrufen:
					<br /><b>{{order._restaurant_name}}: <a href="tel:{{order._restaurant_phone}}" target="_blank">{{ order._restaurant_phone | formatPhone }}</a></b>
					<br /><br />
				</p>
			</div>
			<div class="divider"></div>

			<div class="order-icon"><div class="icon-support"></div></div>
			<div class="order-info">
				<p>
					<span class="hide-mobile">Wenn du Hilfe mit der Webseite brauchst, schreib uns eine Nachricht.</span>
					<span class="hide-desktop">Du kannst Crunchbutton unter dieser Nummer erreichen:</span>
					<br /><b>Crunchbutton: <a href="sms:6467831444" target="_system">{{ '6467831444' | formatPhone }}</a></b>
				</p>
			</div>
			<div class="divider"></div>
		</div>

		<div class="divider dots spacer-two-two hide-desktop" ng-if="order.id"></div>

		<div class="content-padding-mobile two-col" ng-if="order.id">

			<div class="order-icon">
				<div ng-show="(order.delivery_type == 'delivery')" class="icon-delivery"></div>
				<div ng-hide="(order.delivery_type == 'delivery')" class="icon-takeout"></div>
			</div>
			<div class="order-info order-info-oneline">
				<p>
					<span ng-show="(order.delivery_type == 'delivery')">
						<p ng-show="!order.date_delivery_formatted">Bestellung zum Liefern</p>
						<p ng-show="order.date_delivery_formatted" class="order-info-address">Grob geschätzter Lieferzeitpunkt: {{order.date_delivery_formatted}}</p>
					</span>
					<span ng-hide="(order.delivery_type == 'delivery')">Bestellung zum Abholen</span>
				</p>
			</div>
			<div class="divider"></div>

			<div class="order-icon">
				<div ng-show="(order.pay_type == 'card')" class="icon-card"></div>
				<div ng-hide="(order.pay_type == 'card')" class="icon-cash"></div>
			</div>
			<div class="order-info order-info-oneline">
				<p>
					<span ng-show="(order.pay_type == 'card')">
						Paid <b>$<span ng-bind-html-unsafe="order.charged | formatPrice"></span></b>
						<span ng-show="order.campus_cash">&nbsp;mit <b>{{order.campus_cash_name}}</b>
						<span ng-show="order.campus_cash_number"> - <b>{{order.campus_cash_number}}</b></span>
						</span>
						<span ng-show="!order.campus_cash">&nbsp;mit Karte <span ng-show="order.card_ending">endet in <b>{{order.card_ending}}</b>
						</span>
						</span>
						<div class="credit" ng-show="!order.reward_delivery_free && (order.credit && order.credit > 0)">( ${{order._credit}} credit )</div>
					</span>
					<span ng-hide="(order.pay_type == 'card')">Bezahle <b>$<span ng-bind-html-unsafe="order.charged | formatPrice"></span></b> <span ng-show="(order.delivery_type == 'delivery')"> und gebe ein Trinkgeld /span> mit <b>Bargeld</b></span>
				</p>
			</div>

			<div class="divider"></div>


			<div class="order-icon"><div class="icon-user"></div></div>
			<div class="order-info">
				<p>
					{{order.name}}
					<br>{{ order.phone | formatPhone }}
				</p>
			</div>
			<div class="divider"></div>


			<span ng-if="order.delivery_type == 'delivery'">
				<div class="order-icon"><div class="icon-map-home"></div></div>
				<div class="order-info">
					<p class="order-info-address"><a href="{{order.mapLink}}" target="_system"><span ng-bind-html-unsafe="order.address | nl2br"></span></a></p>
					<br />
				</div>
				<div class="divider"></div>
			</span>

			<div ng-hide="(order.delivery_type == 'delivery')">
				<div class="order-icon"><div class="icon-map-restaurant"></div></div>
				<div class="order-info">
					<p class="order-info-address"><a href="{{order.mapLink}}" target="_system"><span ng-bind-html-unsafe="order._restaurant_address | nl2br"></span></a></p>
				</div>
				<div class="divider"></div>
			</div>

		</div>

	</div>

	<div class="divider dots spacer-one-two" ng-if="order.id"></div>

	<div class="content-padding" ng-if="order.id">
		<? /*
		<div class="credit" ng-if="!order.reward_delivery_free && (order.credit && order.credit > 0)">( ${{order._final_price}} - ${{order._credit}} credit )</div>
*/ ?>
		<a href="<?=$this->export ? '{{server}}' : ''?>printorder/{{ order.uuid }}" target="_system" class="print-icon"><button class="button lightorange"><i class="fa fa-print"></i>&nbsp;&nbsp;&nbsp;Quittung drucken</button></a>
	</div>


</div>
