<div class="top-pad"></div>

<div class="owners-bubble-wrap noselect">
	<div class="bubble-tail bubble-tail-beige bubble-animated">
		<div class="text" ng-switch="ownerMessage">
			<span class="single-line" ng-switch-when="1">Verstanden?</span>
			<span class="single-line" ng-switch-when="2"><b>SCHÖN</b> für dich!!</span>
			<span ng-switch-when="3">Jetzt aber im Ernst</span>
			<span ng-switch-when="4">Du solltest wirklich Crunchbutton benutzen</span>
			<span ng-switch-when="5">Wir haben die besten Kunden</span>
			<span class="single-line" ng-switch-when="6">Sie lieben uns geradezu</span>
			<span class="small" ng-switch-when="7">Und wir können diese <br>Liebe<br> mit dir teilen</span>
			<span ng-switch-when="8">Natürlich ist das nicht ganz billig</span>
			<span ng-switch-when="9">Man bekommt im Leben nichts geschenkt</span>
			<span class="single-line" ng-switch-when="10">Nicht mal Liebe</span>
			<span class="single-line" ng-switch-when="11">Außer von mir</span>
			<span class="single-line" ng-switch-when="12">Ich hab dich lieb.</span>
			<span ng-switch-when="13">Das war jetzt gratis</span>
			<span class="single-line" ng-switch-when="14"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
			<span ng-switch-default><b>Wir sind gut</b><br>für dein Geschäft!</span>
		</div>
		<div class="bubble-tail-spacer"></div>
	</div>
	<div class="owner-brocoli animated-resize" ng-instant="ownerMessage = (ownerMessage > 13 ? 0 : (ownerMessage + 1))"></div>
	<div class="divider"></div>
</div>

<div class="content-padding owner-content" ng-controller="SupportCtrl">
	<br />

	<p>Wir wählen das besten Essen aus, dass Kunden aus der Region lieben. Wir helfen dir dein Restaurant zur besten Version von sich selbst zu machen.</p>
	<br /><br />

	<div class="owner-block">
		<div class="owner-icon"><i class="fa fa-usd"></i></div>
		<div class="owner-text">
			<h4>Keine Kosten im vorraus.</h4>
			<p>Wir verlangen nur einen kleinen Prozentsatz, aber den kannst du ja an deine Kunden durchreichen -- sogar die Kreditkartengebühren.</p>
		</div>
	</div>
	<div class="divider"></div>

	<div class="owner-block">
		<div class="owner-icon"><i class="fa fa-heart"></i></div>
		<div class="owner-text">
			<h4>Kunden lieben uns.</h4>
			<p>Kurz gesagt sind wir die am einfachsten zu bedienende Online Bestellplattform auf der Welt. Kunden können ihren Bestellungen mit nur einem Knopfdruck wiederholen. Wir machen es einfach für Kunden ihre Lieblingsdinge anzuschauen und zu bestellen. Und wenn du dich qualifizierst, markieren wir dich für sie als Favoriten.</p>
		</div>
	</div>

	<div class="divider"></div>

	<div class="owner-block">
		<div class="owner-icon"><i class="fa fa-star"></i></div>
		<div class="owner-text">
			<h4>Es ist gut fürs Geschäft.</h4>
			<p>Deine beliebtesten Gerichte werden als Favoriten beworben. Eine Woche nachdem wir in New Haven gestartet sind, haben wir Bestellung von $9K pro Monat für unsere Restaurants gemacht.</p>
		</div>
	</div>
	<br><br>
	<a href="mailto:{{join}}"><button class="button green">Schick uns eine E-Mail</button></a>
	<br><br>
	<p class="alternate-link"><a href="tel:+18003514161">Oder ruf uns an @ 800-351-4161</a></p>
</div>
