<!-- Gift card messages -->
<div class="giftcard-info">

	<div class="warning" ng-if="giftcard.removed" class="giftcard-error">
		Du hast gerade einen Gutschein entfernt. Wenn du ihn immernoch benutzen willst, musst du ihn wieder eintragen.
	</div>

	<div ng-if="restaurant.giftcard == 0 && giftcard.hasGiftCards" class="giftcard-error">
		Dieses Restaurant nimmt keine Gutscheine an.
	</div>

	<div ng-if="giftcard.hasValue && order.form.pay_type == 'cash' " class="giftcard-error">
		Du musst mit Karte bezahlen, um deinen {{AB.dollar}}{{giftcard.value}} Gutschein zu nutzen!</span>
	</div>

	<div ng-repeat="success in giftcard.giftcards.success">
		<div ng-if="success.delivery_free && restaurant.delivery == '1' && order.form.delivery_type=='delivery'">
			<span ng-if="order.form.pay_type == 'card'">{{success.message}}</span>
			<div class="giftcard-error" ng-if="order.form.pay_type == 'cash'">Du musst mit Karte bezahlen, um deine Lieferunggebühren gratis zu bekommen</div>
		</div>
	</div>

	<div ng-if="restaurant.giftcard == 1 && order.form.pay_type == 'card' ">

		<!-- Gift card success -->
		<div ng-repeat="success in giftcard.giftcards.success">
			<div ng-if="!success.delivery_free && !success.message">
				<div ng-if="!success.error">
					Der Gutschein ({{success.giftcard}}) bringt dir ${{success.value}}.
				</div>
				<div ng-if="success.error == 'other restaurant'">
					Der Gutschein ({{success.giftcard}}) den du benutzen willst, gehört zu einem anderen Restaurant.
				</div>
			</div>
			<div ng-if="success.message">
				{{success.message}}
			</div>
		</div>
	</div>

	<div>
		<!-- Gift card errors -->
		<div ng-repeat="error in giftcard.giftcards.error" class="giftcard-error">
			<div ng-switch on="error.error">
				<div ng-switch-when="gift card already used">
					Der Gutschein ({{error.giftcard}}) wurde bereits eingelöst.
				</div>
				<div ng-switch-when="custom">
					{{error.message}}
				</div>
			</div>
		</div>
		<span ng-if="giftcard.justOneGiftCardError">
			Du kannst nur einen Gutschein auf einmal nutzen.
		</span>

	</div>

</div>
