<div class="restaurant-suggestion-container zoom-anim-dialog mfp-hide dialog mfp-hide">

	<div ng-controller="RestaurantSuggestionCtrl">

		<div ng-if="tab == 'form'">

			<div class="dialog-padding">

				<p class="suggestion-header">Was gibts?</p>
				<div class="support-form-group form-group">
					<textarea ng-autosize ng-focus="softKeyboardModal($event)" ng-model="suggestion.content" class="form-input form-field"></textarea>
				</div>

				<div class="divider spacer-one-onehalf"></div>

				<p class="suggestion-header">Wenn du was bestimmtes auf der Karte haben willst, gibt es hier ein:</p>
				<div class="support-form-group form-group">
					<textarea ng-autosize ng-focus="softKeyboardModal($event)" ng-model="suggestion.add_more_content" class="form-input form-field"></textarea>
				</div>

			</div>
			
			<div class="dialog-divider"></div>

			<div class="dialog-padding dialog-bottom-buttons">
				<div class="button-pushable">
					<button class="button green" ng-click="send_form()">Abschicken</button>
				</div>
			</div>


		</div>

		<div ng-if="tab == 'thank-you'">

			<div class="dialog-padding">
				<p class="suggestion-thanks">Dankeschön!</p>
				<div class="location-gorillia animated-resize shake"></div>
				<button class="button green" ng-click="close()">Bring mich zurück</button>
			</div>

		</div>

	</div>

</div>
