<div class="delivery-payment-info restaurant-side-bar restaurant-side-user-info" ng-if="order.loaded && ( restaurant._open || restaurant.force_pre_order ) && !order.showForm && order.cart.hasItems()">

	<div class="divider dots"></div>

	<div class="content-padding">

		<span class="hide-mobile">
			<a ng-click="order.showForm=true" class="order-change-info-link">Daten ändern</a>
			<div class="divider dots spacer-one-two"></div>
		</span>

		<div class="order-icon">
			<i class="fa fa-phone payment-form-icon form-icon form-field"></i>
		</div>
		<div class="order-info order-info-oneline">
			<p>
				<span ng-if="user.phone">{{ user.phone | formatPhone }}</span>
				<span ng-if="!user.phone">Keine Telefonnummer angegeben</span>
			</p>
		</div>
		<div class="divider"></div>
		<div class="order-icon">
			<i class="fa fa-birthday-cake gift-card-balance payment-form-icon form-icon form-field" ng-if="order.form.pay_type=='card' && order.total() <= credit.number"></i>
			<i class="fa fa-credit-card payment-form-icon form-icon form-field" ng-if="order.form.pay_type=='card' && order.total() > credit.number"></i>
			<i class="fa fa-money payment-form-icon form-icon form-field" ng-if="order.form.pay_type=='cash'"></i>
		</div>
		<div class="order-info order-info-oneline">

			<p>
				<span ng-if="order.form.pay_type=='card' && order.total() <= credit.number">Gutschein Guthaben</span>
				<span ng-if="order.form.pay_type=='card' && credit.number && order.total() > credit.number">Gutschein hat noch {{user.card_ending}} &amp; - {{credit.value}} übrig</span>
				<span ng-if="order.form.pay_type=='card' && !credit.number">Karte hat noch {{user.card_ending}}</span>
				<span ng-if="order.form.pay_type=='cash'">Bezahhle mit <b>Bargeld</b>
					<span ng-if="config.driver_change_amount">
						<br><i>Fahrer haben nur ${{config.driver_change_amount}} Wechselgeld dabei.</i>
					</span>
				</span>
			</p>
		</div>
		<div class="divider"></div>


		<div class="order-icon">
			<i class="fa fa-map-marker payment-form-icon form-icon form-field"></i>
		</div>
		<div class="order-info" ng-if="restaurant.delivery == '1' && order.form.delivery_type=='delivery'">
			<p>
				Delivered to:<br />
			</p>
			<p class="restaurant-info-address">
				<span ng-bind-html-unsafe="order.form.address | nl2br"></span>
				<i ng-hide="order.form.address">Keine Adresse angegeben</i>
			</p>
		</div>
		<div class="order-info" ng-if="restaurant.takeout == '1' && order.form.delivery_type=='takeout'">
			<p class="restaurant-info-address">
				Abholung bei:<br />
				<span ng-bind-html-unsafe="restaurant.address | nl2br"></span>
			</p>
		</div>


		<div class="divider"></div>

				<div class="payment-form-group form-group">

					<i class="fa fa-bullhorn payment-form-icon form-icon form-field"></i>
					<textarea ng-focus="softKeyboard($event);" ng-blur="checkGiftCard();softKeyboardExit()" ng-autosize name="notes" ng-model="order.form.notes" tabindex="6" class="payment-form-input form-input form-field notes-text-area" placeholder="Anmerkungen / Code"></textarea>

					<ng-include src="'/assets/view/restaurant-gift-card.html'"></ng-include>
		</div>

		<div class="divider"></div>

		<div class="divider spacer-one-two"></div>

		<p>Wir haben deine Adresse und Bezahlmethode gespeichert, damit du mit nur einem Klick wieder bestellen kannst</p>

		<div class="divider spacer-one-two"></div>

		<span class="hide-desktop">
   		<a ng-click="order.showForm=true" class="order-change-info-link-mobile">Daten ändern</a>
   		<div class="divider dots spacer-one-two"></div>
		</span>

		<ng-include src="'/assets/view/restaurant-form-delivery-time.html'"></ng-include>

		<div class="divider spacer-two-two"></div>

		<span class="hide-mobile">
			<div ng-if="!order.showForm">
				<ng-include src="'/assets/view/restaurant-place-order-button.html'"></ng-include>
			</div>
		</span>

	</div>
</div>
