<div class="bg">
	<div ng-if="!order.loaded">
		<? /* THIS WILL SHOW UP WHEN A RESTAURANT PAGE IS DIRECTLY LOADED FROM A BROWSER BEFORE THE PAGE SHOWS. */ ?>
	</div>

	<div ng-if="restaurant">

		<div class="restaurant-pad"></div>

		<!-- image -->
		<ng-include src="'/assets/view/restaurant-image.html'"></ng-include>

		<!-- main-content-readable-margin -->
		<div class="restaurant-content-body content-padding">
			<div class="restaurant-content-body-background"></div>

			<!-- comment -->
			<ng-include src="'/assets/view/restaurant-comment.html'"></ng-include>

			<div ng-if="restaurant.eta && restaurant._open" class="restaurant-message">Geschätzte Lieferdauer: {{restaurant.eta}} Minuten</div>

			<!-- desktop version -->
			<span class="hide-mobile">
				<ng-include src="'/assets/view/restaurant-desktop.html'"></ng-include>
			</span>

			<!-- mobile version -->
			<span class="hide-desktop">
				<ng-include  src="'/assets/view/restaurant-mobile.html'"></ng-include>
			</span>

			<div class="content-padding hide-mobile" ng-if="config.suggestions && show_suggestions">
				<p>Hast du ein Problem, oder Fragen zu der Speisekarte? <a href class="suggestion-text" ng-click="suggestion();"> Ja!</a></p>
			</div>

		</div>

	</div>

	<!-- total breakdown - mobile only -->
	<span class="hide-desktop">
		<ng-include src="'/assets/view/restaurant-breakdown.html'"></ng-include>
	</span>

	<div class="divider bottom-spacer"></div>

</div>

<ng-include src="'/assets/view/restaurant-message-boxes.html'"></ng-include>
<ng-include src="'/assets/view/restaurant-suggestion.html'"></ng-include>
