<div class="restaurant-closed-container zoom-anim-dialog mfp-hide dialog" ng-controller="RestaurantClosedCtrl">
	<div class="dialog-padding">
		<h1 ng-bind="restaurant.name"></h1>
		<div class="dialog-egg animated-resize"></div>
			<span ng-if="active">
				<p>

					<span ng-if="!acceptingOrders">
						<span ng-if="restaurant.delivery">liefert aktuell nicht, ist aber in dieser Zeitspanne geöffnet</span>
						<span ng-if="!restaurant.delivery">ist aktuell nicht verfügbar, aber normalerweise in diese Zeitspanne geöffnet</span>
					</span>
					<span ng-if="acceptingOrders">
						<span ng-if="restaurant.delivery">ist aktuell nicht verfügbar, ist aber in dieser Zeitspanne wieder für dich da:</span>
						<span ng-if="!restaurant.delivery">ist aktuell nicht verfügbar, ist aber in dieser Zeitspanne wieder geöffnet:</span>
					</span>

<!--					&nbsp;(<span ng-bind="restaurant._tzabbr"></span>):--><br /><br />

				</p>
				<p ng-bind-html-unsafe="closedMessage" class="dialog-hours"></p>
			</span>
			<span ng-if="!active">
				<p>Dieses Restaurant ist gerade nicht verfügbar</p>
			</span>
			<div class="divider"></div>

	</div>
	<div class="dialog-divider"></div>
	<div class="dialog-padding dialog-bottom-buttons">
		<div class="button-pushable"><button class="button lightorange" ng-click="closePopup()">Ok</button></div>
	</div>
</div>

