<div class="top-pad"></div>

<div class="restaurants-top-wrap content-padding">
	<div class="restaurants-top-tag hide-mobile" ng-if="slogan">
		<h4 ng-bind-html-unsafe="slogan" class="restaurants-top-title"></h4>
		<p ng-bind-html-unsafe="tagline"></p>
		<p ng-if="operation_hours" class="operation-hours">
			Crunchbutton liefert: <br><span ng-bind-html-unsafe="operation_hours"></span>
		</p>
		<p><br>{{entered}} - <a href="/location" title="Change">Ändern</i></a></p>
	</div>

	<div class="hide-desktop">
		<p ng-if="operation_hours" class="operation-hours content-padding">
			<strong>Crunchbutton liefert:</strong>
			<br><span ng-bind-html-unsafe="operation_hours"></span>
			<div class="divider"></div>
			<br><br>
		</p>
	</div>

	<div class="restaurants-bubble-wrap noselect">
		<div ng-if="!image">
			<div ng-if="!allClosed && restaurants">
				<div class="bubble-tail bubble-tail-green bubble-animated">
					<div class="text" ng-switch="pushMessage">
						<span ng-switch-when="1">Wir wählen<br>das beste Essen...</span>
						<span ng-switch-when="2">Von den besten Restaurants...</span>
						<span ng-switch-when="3">Damit du wengiger<br> Arbeit hast!</span>
						<span ng-switch-when="4">Nie mehr viel<br> zu großen Speißekarten!</span>
						<span class="single-line" ng-switch-when="5">Nie mehr schlechtes Essen!!</span>
						<span ng-switch-when="6">Wir haben nur das gute Zeug!</span>
						<span class="single-line" ng-switch-when="7">Hast du einen Vorschlag?</span>
						<span ng-switch-when="8">Willst du für<br> uns arbeiten?</span>
						<span class="single-line" ng-switch-when="9">Schreib uns!</span>
						<span ng-switch-when="10">Wir suchen immer nach...</span>
						<span ng-switch-when="11" class="single-line">Tollen Leuten...</span>
						<span class="single-line" ng-switch-when="12">Und dem besten Essen!</span>
						<span class="single-line" ng-switch-when="13"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
						<span ng-switch-default class="restaurants-push-tagline">
							<span class="hide-desktop"><b>Push a button</b><br>Lass die Essen liefern!</span>
							<span class="hide-mobile">Wähle ein <br><b>Restaurant</b></span>
						</span>

					</div>
					<div class="bubble-tail-spacer"></div>
				</div>
				<div class="restaurants-orange" ng-instant="pushMessage = (pushMessage > 12 ? 0 : (pushMessage + 1))" instant-pass-thru></div>
			</div>

			<div ng-if="allClosed">
				<div class="bubble-tail bubble-tail-green bubble-animated noselect">
					<div class="text" ng-switch="pushMessage">
						<span ng-switch-when="1">Wir sind bald wieder da.</span>
						<span ng-switch-when="2" class="small">Kennst du gute Restaurants in deiner Gegend?</span>
						<span ng-switch-when="3">Willst du Fahrer werden?</span>
						<span class="single-line" ng-switch-when="4">Schreib uns eine Nachricht...</span>
						<span class="single-line" ng-switch-when="5">Und lass uns das machen!</span>
						<span class="single-line" ng-switch-when="6"><i class="fa fa-cutlery"></i> <i class="fa fa-cutlery"></i> <i class="fa fa-cutlery"></i></span>
						<span ng-switch-default class="restaurants-push-tagline">
							<span ng-if="community_closed" class="small">
								{{community_closed}}
							</span>
							<span ng-if="!community_closed && !openSoon"><b>Wahhhhhh!!!</b><br>Keine Lieferung verfügbar</span>
							<span ng-if="!community_closed && openSoon">Lieferung bald verfügbar!!</span>
						</span>
					</div>
					<div class="bubble-tail-spacer"></div>
				</div>
				<div class="restaurants-orange restaurants-orange-sad" ng-instant="pushMessage = (pushMessage > 6 ? 0 : (pushMessage + 1))" instant-pass-thru></div>
			</div>

			<div class="divider"></div>
			<br>

			<? /*
			<div class="restaurants-tagline">
				<h2><i class="fa fa-hand-o-right"></i>&nbsp;&nbsp;Choose a restaurant</h2>
			</div>
			*/?>
		</div>

		<div ng-if="image" class="community-image"></div>


		<div class="divider"></div>
	</div>
	<div class="divider"></div>

</div>

<div ng-if="restaurants">
	<div class="restaurants-items">

	<span ng-repeat="restaurant in restaurants | limitTo:restaurantsToShow" class="restaurants-repeated">
		<ng-include src="'/assets/view/restaurants-box-restaurant.html'"></ng-include>
	</span>
	<div class="divider"></div>

	<button class="button green restaurants-more" ng-if="restaurantsToShow < restaurants.length" ng-click="showMoreRestaurants()">
		Mehr tolle Restaurants
	</button>

	</div>
</div>

<div class="content-padding suggestion-footer" ng-if="config.suggestions && show_suggestions">
	<p>Willst du was anderes geliefert bekommen? <a href class="suggestion-text" ng-click="suggestion();"> Sag uns Bescheid!</a></p>
</div>

<ng-include src="'/assets/view/restaurants-suggestion.html'"></ng-include>
