<div splash-position-fix class="bg home-top splash-top fixed parallax-bg">
	<div class="splash-spacer-one"></div>
	<div title="Crunchbutton" class="logo animated-resize" ng-click="navigation.home()"></div>
	<div class="splash-spacer-two"></div>

	<div class="about-green-orange-scene noselect" fixed-height="170">
		<div class="splash-bubble-wrap">
			<div class="bubble-curved bubble-curved-white bubble-animated animated-resize">
				<div class="text" ng-switch="splashMessage">
					<span class="single-line" ng-switch-when="1">Hey!!</span>
					<span class="single-line" ng-switch-when="2">Versuch mal dich anzumelden!</span>
					<span class="single-line" ng-switch-when="3">Nein, da unten!</span>
					<span ng-switch-when="4">Das wird<br>oberaffengeil</span>
					<span ng-switch-when="5">Ich sehe, dass du aufgeregt bist</span>
					<span class="small" ng-switch-when="6">Vielleicht etwas zu aufgeregt, mir zu folgen</span>
					<span class="small" ng-switch-when="7">Aber die nächste Seite ist noch spannender!</span>
					<span class="single-line" ng-switch-when="8">Du schaffst das!</span>
					<span class="single-line" ng-switch-when="9">Ich glaub an dich!</span>
					<span class="single-line" ng-switch-when="10">Du bist super!</span>
					<span class="single-line" ng-switch-when="11">Log in!</span>
					<span class="single-line" ng-switch-when="12">YA!</span>
					<span ng-switch-when="13">Es gibt ein Kuh Level</span>
					<span ng-switch-when="14">Snape tötet Dumbledore.</span>
					<span class="small" ng-switch-when="15">Rubber baby buggy bumpers.</span>
					<span class="small" ng-switch-when="16" style="margin-top: 1.2em;">
						<i class="fa fa-arrow-circle-up"></i>
						<i class="fa fa-arrow-circle-up"></i>
						<i class="fa fa-arrow-circle-down"></i>
						<i class="fa fa-arrow-circle-down"></i>
						<i class="fa fa-arrow-circle-left"></i>
						<i class="fa fa-arrow-circle-right"></i>
						<i class="fa fa-arrow-circle-left"></i>
						<i class="fa fa-arrow-circle-right"></i>
						B
						A
					</span>
					<span class="single-line" ng-switch-when="17">@#%*@%&!</span>


					<span class="single-line" ng-switch-when="18"><i class="fa fa-heart"></i> <i class="fa fa-heart"></i> <i class="fa fa-heart"></i></span>
					<span class="single-line" ng-switch-default>Oh, Hallo!&nbsp;&nbsp;</span>
				</div>
			</div>
			<div class="bubble-curved-spacer"></div>
		</div>

		<div class="about-green-orange animated-resize" ng-instant="splashMessage = (splashMessage > 17 ? 0 : (splashMessage + 1))" instant-pass-thru></div>
	</div>
	<div class="divider"></div>

	<div class="splash-bottom fixed-599">
		<div class="splash-inputs">
			<p class="splash-tagline">
				<b>Wir sind Crunchbutton.</b>
				<br>Wir liefern dir das beste Essen von Restaurants in deiner Nähe.
			</p>
			<div class="button-pushable">
				<button class="button facebook" ng-click="facebook.auth()">
					<i class="fa fa-facebook-square"></i>&nbsp;
					<span ng-if="!facebook.facebook.wait">Mit Facebook anmelden</span>
					<span ng-if="facebook.facebook.wait">Einen Moment
						<div id="circleG">
							<div id="circleG_1" class="circleG"></div>
							<div id="circleG_2" class="circleG"></div>
							<div id="circleG_3" class="circleG"></div>
						</div>
					</span>
				</button>
			</div>

			<p class="center-text">
				<a href="" class="splash-continue" ng-instant="navigation.link('/location','fade')">Weiter ohne Anmeldung</a>
			</p>
		</div>
	</div>

</div>
