

<div class="content-padding noselect">
	<div class="jobs-bubble-wrap">
		<div class="bubble-curved bubble-curved-green bubble-animated animated-resize">
			<div class="text" ng-switch="orangeMessage">
				<span ng-switch-when="1">Gratis Lieferungen</span>
				<span ng-switch-when="2">Gratis pinker Gorilla</span>
				<span class="single-line" ng-switch-when="3">Gratis Umarmungen</span>
				<span ng-switch-when="4">Das ist doch mal was gutes!</span>
				<span ng-switch-when="5">Was willst du mehr?</span>
				<span ng-switch-when="6">Gutes Wetter?</span>
				<span ng-switch-when="7">Nette Leute?</span>
				<span ng-switch-when="8">Ja, die haben wir auch!</span>
				<span class="small" ng-switch-when="9">Schick uns eine Nachricht und trinke ein Bier mit uns!</span>
				<span class="single-line" ng-switch-when="10"><i class="fa fa-beer"></i> <i class="fa fa-beer"></i> <i class="fa fa-beer"></i></span>
				<span class="single-line" ng-switch-default><b>BIER!</b></span>
			</div>
		</div>
	</div>

	<div class="home-join-us" ng-instant="orangeMessage = (orangeMessage > 9 ? 0 : (orangeMessage + 1))" instant-pass-thru></div>
	<div class="divider"></div>
</div>

<br />
<div class="content-padding col-box" ng-controller="SupportCtrl">

	<div class="two-col">
		<h4>Verdiene gratis Essen</h4>
		<p>
			Verdiene Punkte indem du Essen bestellst, deine Bestellungen auf Social Media teilst oder Freunde anwirbst.
		</p>
		<br />
		<br /><br /><br /><br />
	</div>

	<div class="two-col">
		<h4>Fahrer</h4>
		<p>
			Was ist besser als Lieferessen? Essen liefern! Wenn du ein Smartphone, eine Auto und eine Versicherung hast, schick uns eine Nachricht!
		</p>
		<br />
		<a href ng-click="navigation.link('/drivers/apply','push')"><button class="button lightorange">apply now</button></a>
		<br /><br /><br /><br />
	</div>

	<div class="two-col">
		<h4>Community Manager</h4>
		<p>Manages the local team of brand reps to market Crunchbutton and establish us as a local staple.</p>
		<br />
		<a href="mailto:{{resumes}}"><button class="button lightorange">Apply Now</button></a>
		<br /><br /><br /><br />
	</div>


	<div class="two-col">
		<h4>Brand Reps</h4>
		<p>Representatives that work as a team to inform their community about Crunchbutton through flyering, talking to potential customers and leveraging their social media presence.
		</p>
		<br />
		<a href ng-click="navigation.link('/reps/apply','push')"><button class="button lightorange">join up</button></a>
		<br /><br /><br /><br />
	</div>


	<div class="two-col">
		<h4>Entwickler &amp; Designers</h4>
		<p>Look at this beautiful website! It's almost perfect! You know what would make it better? Your magical touch! Join our small team of developers located in Los Angeles and let's get shit done! More exclamation points!!!</p>
		<br />
		<a href="mailto:{{devs}}"><button class="button lightorange">rock out</button></a>
		<br /><br /><br /><br />
	</div>


	<div class="two-col">
		<h4>Apply to intern for us in LA</h4>
		<p> Looking for a "Jack-of-all-trades" to help us out in all aspects of our business. We're growing at an unbelievable rate, and we want someone interested in getting experience in every department of a growing food delivery company. You'll learn your way around and become an integral part of our operations!</p>
		<br />
		<a href="mailto:{{recruiting}}"><button class="button lightorange">apply now</button></a>
		<br /><br /><br /><br />
	</div>

	<div class="two-col">
		<div>
			<h4>Wer seid ihr?!</h4>
			<p>Wir sind Menschen! Menschen, die das Essen so sehr lieben, dass wir unsere Leidenschaft teilen möchten. Und dass ohne dich zu bitten dein Zuhause zu verlassen.</p>
			<br>
			<button class="button green" ng-click="navigation.link('/about','push')">Meet the team</button>
			<br /><br /><br /><br />
		</div>
	</div>


</div>


