crunchbutton:
  build: .
  ports:
   - "8000:80"
  links:
   - crunchbutton-db-dev
  environment:
   - DEBUG=1
   - COMPOSE=1
   - ENV=DOCKER
   - DATABASE_URL=mysql://root:root@crunchbutton-db-dev:3306/crunchbutton
  command: bash -c "sleep 60 && /app/cli/build.sh && nginx && php-fpm"
  hostname: crunchbutton
  restart: unless-stopped
  
cockpit:
  build: .
  ports:
   - "8001:80"
  links:
   - crunchbutton-db-dev
  environment:
   - DEBUG=1
   - COMPOSE=1
   - ENV=DOCKER
   - THEME=cockpit2
   - ADMIN_LOGIN=admin
   - ADMIN_PASSWORD=admin
   - ADMIN_PHONE=12345
   - DATABASE_URL=mysql://root:root@crunchbutton-db-dev:3306/crunchbutton
  command: bash -c "sleep 60 && /app/cli/build.sh && cd /app && php cli/install.php && nginx && php-fpm"
  hostname: cockpit
  restart: unless-stopped

crunchbutton-db-dev:
  build: db
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_ROOT_USER=root
   - MYSQL_USER=admin
   - MYSQL_PASS=pass
   - MYSQL_DATABASE=crunchbutton
  ports:
   - "3306:3306"
  hostname: crunchbutton-db-dev
  restart: unless-stopped
