

<? if ($this->restaurant->id_restaurant) : ?>
	<meta property="og:title" content="<?=$this->restaurant->name?> auf Crunchbutton">
	<meta property="og:description" content="Essen von <?=$this->restaurant->name?> mit einem Klick bestellen. Wir finden die besten Restaurants <?=$this->community->prep?> <?=$this->community->name?> and machen das Bestellen deiner Lieblingsgerichte so leicht wie eine Feder.">
	<? if ($this->restaurant->image()) : ?>
		<?php if( $this->restaurant->facebook() ) { ?>
			<meta property="og:image" content="http://<?=$_SERVER['HTTP_HOST']?>/cache/images/<?=$this->restaurant->facebook()->getFileName()?>">
		<?php } ?>
	<? else : ?>
		<meta property="og:image" content="http://<?=$_SERVER['HTTP_HOST']?>/assets/images/facebook-like.png">
	<? endif ; ?>

<? elseif ($this->community->id_community) : ?>
	<meta property="og:title" content="Crunchbutton - Mit einem Klick Essen aus <?=$this->community->name?> bestellen">
	<meta property="og:description" content="Wir bringen dein Lieblingsrestaurant <?=$this->community->prep?> <?=$this->community->name?> direkt an deine Haustür. Lass dir Sachen von Orten liefern, die nicht liefern. Bestell dein Lieblingsgericht mit nur einem Knopfdruck.">
	<? foreach ($this->community->restaurants() as $restaurant) : ?>
		<? if ($restaurant->image() && $restaurant->facebook() ) : ?>
			<meta property="og:image" content="http://<?=$_SERVER['HTTP_HOST']?>/cache/images/<?=$restaurant->facebook()->getFileName()?>">
		<? else : ?>
			<meta property="og:image" content="http://<?=$_SERVER['HTTP_HOST']?>/assets/images/facebook-like.png">
		<? endif ; ?>

		<? break;?>
	<? endforeach; ?>

<? else : ?>
	<meta property="og:title" content="Crunchbutton - Mit einem Klick Essen bestellen">
	<meta property="og:description" content="Wir bringen dein Lieblingsrestaurant direkt an deine Haustür. Lass dich von Orten beliefern, die nicht liefern. Bestell dein Lieblingsgericht mit nur einem Knopfdruck.">
	<meta property="og:image" content="http://<?=$_SERVER['HTTP_HOST']?>/assets/images/facebook-like.png">
<? endif ; ?>

<meta property="og:type" content="company">
<meta property="og:url" content="https://<?=$_SERVER['HTTP_HOST']?><?=$_SERVER['REQUEST_URI']?>">
<meta property="og:site_name" content="Crunchbutton">
<meta property="fb:app_id" content="411729638889643">

<? if ($_SERVER['__HTTP_HOST'] == 'crunchbutton.com') : ?>
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
		ga('create', 'UA-36135548-1', 'crunchbutton.com');
		ga('require', 'ecommerce', 'ecommerce.js');
		ga('require', 'displayfeatures');
		ga('send', 'pageview');
	</script>
<? endif ; ?>
